### ISSUE TITLE
Show top object types

### ISSUE THREAD

**Issue by brauliobo** [zombocom/heapy#20]
First of all, thanks for the great work!

I've had a hard time debugging a memory leak during several days and could finally find the problem.
`heapy` helped a bit, but it lacked one important information about the object types.

Basically printing the counts of objects type per class like done in
https://github.com/drbrain/net-http-persistent/issues/96 

Is this possible to be done through heap dumps?

**Comment by schneems** [comment]
Sorry for the extreme delay. I also wanted to mention that https://github.com/SamSaffron/memory_profiler is a great option for inspecting objects like you did in the attached issue.

I was not sure if that data is present or easy to find in a heap dump so I did some exploring:

Generate heap dump:

```ruby
require 'objspace'
ObjectSpace.trace_object_allocations_start

class FooGrep
end

100.times do
  FooGrep.new
end

io=File.open("/tmp/my_dump", "w")
ObjectSpace.dump_all(output: io);
io.close
```

We can see the FooGrep class in there:

```
{"address":"0x7fe77e02d4c0", "type":"CLASS", "class":"0x7fe77e02d498", "name":"FooGrep", "references":["0x7fe77b8c5248", "0x7fe77f84e5b8"], "file":"scratch.rb", "line":4, "generation":9, "memsize":464, "flags":{"wb_protected":true}}
```

Then if we search for objects with a `"class"` of 0x7fe77e02d4c0 we find all our objects:

```
{"address":"0x7fe77f022920", "type":"OBJECT", "class":"0x7fe77e02d4c0", "ivars":0, "file":"scratch.rb", "line":8, "method":"new", "generation":9, "memsize":40, "flags":{"wb_protected":true}}
{"address":"0x7fe77f022948", "type":"OBJECT", "class":"0x7fe77e02d4c0", "ivars":0, "file":"scratch.rb", "line":8, "method":"new", "generation":9, "memsize":40, "flags":{"wb_protected":true}}
{"address":"0x7fe77f022970", "type":"OBJECT", "class":"0x7fe77e02d4c0", "ivars":0, "file":"scratch.rb", "line":8, "method":"new", "generation":9, "memsize":40, "flags":{"wb_protected":true}}
# ...
```

So it is possible to get a count of objects based on class. That could be an interesting way to view heap dump contents. 

I don't have immediate plans to work on this right now, but if someone wants to send a PR or discuss this work some more, feel free to work on it.
